---
name: "Nix Format"
description: "Format Nix files using alejandra"

inputs:
  path:
    description: "Files or directories"
    required: false

outputs:
  logs:
    description: "Logs of alejandra"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
