---
name: "Nix Format"
description: "Format Nix files using alejandra"

inputs:
  working_directory:
    description: "Directory for running action"
    required: false

outputs:
  logs:
    description: "Logs of alejandra"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working_directory }}
