---
name: "Nix Format"
description: "Format Nix files with alejandra"

inputs:
  working-directory:
    description: "Directory for running the action"
    required: false

outputs:
  logs:
    description: "Logs of alejandra"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working-directory }}
