---
name: "Ansible Lint"
description: "Lint Ansible files using ansible-lint"

inputs:
  path:
    description: "Files or directories"
    required: false
  config_file:
    description: "Configuration file to use"
    required: false
  strict:
    description: "Return non-zero exit code on warnings as well as errors"
    required: false
    default: "false"

outputs:
  logs:
    description: "Logs of ansible-lint"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.config_file }}
    - ${{ inputs.strict }}
