---
name: "Ansible Lint"
description: "Lint Ansible files using ansible-lint"

inputs:
  lintables:
    description: "One or more files or paths"
    required: false
  config_file:
    description: "Specify configuration file to use"
    required: false
  strict:
    description: "Return non-zero exit code on warnings as well as errors"
    required: false
    default: "false"

outputs:
  logs:
    description: "Logs of ansible-lint"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.lintables }}
    - ${{ inputs.config_file }}
    - ${{ inputs.strict }}
