---
name: "Molecule"
description: "Ansible unit testing using molecule"

inputs:
  working_directory:
    description: "Directory for running the action"

outputs:
  logs:
    description: "Logs of molecule"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working_directory }}
