---
name: "Molecule"
description: "Ansible unit testing using molecule"

inputs:
  working_directory:
    description: "Directory for running the action"
    required: true

runs:
  using: "composite"

  steps:
    - name: Install molecule dependencies
      shell: bash
      run: >
        pip install molecule==24.12.0 molecule-plugins[docker]==23.6.0

    - name: Run molecule
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: >
        molecule test
      env:
        ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/${{ inputs.working_directory }}/${{ env.ANSIBLE_VAULT_PASSWORD_FILE }}
        ANSIBLE_FORCE_COLOR: 1
