---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER

FLAVOR_SUGGESTIONS: false
GITHUB_COMMENT_REPORTER: true
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

BASH_SHELLCHECK_ARGUMENTS: --external-sources --exclude=SC2129
BASH_SHFMT_ARGUMENTS: --indent 4 --space-redirects
COPYPASTE_JSCPD_DISABLE_ERRORS: true
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (^\.github/PULL_REQUEST_TEMPLATE\.md$)
REPOSITORY_KICS_DISABLE_ERRORS: true
REPOSITORY_TRIVY_DISABLE_ERRORS: true
YAML_YAMLLINT_ARGUMENTS: --strict
