---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

FLAVOR_SUGGESTIONS: false
GITHUB_COMMENT_REPORTER: true
SECURITY_SUGGESTIONS: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

BASH_SHFMT_ARGUMENTS: --indent=4 --space-redirects
COPYPASTE_JSCPD_DISABLE_ERRORS: true
YAML_YAMLLINT_ARGUMENTS: --strict
