---
name: "Yaml Lint"
description: "Lint Yaml files using yamllint"

inputs:
  working_directory:
    description: "Directory for running the action"
    required: false
  config_file:
    description: |
      Configuration file, relative to the working directory
      Will use default configuration if not provided
    required: false
  strict:
    description: "Return non-zero exit code on warnings as well as errors"
    default: "true"
    required: false

outputs:
  logs:
    description: "Logs of yamllint"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working_directory }}
    - ${{ inputs.config_file }}
    - ${{ inputs.strict }}
