---
name: "Yaml Lint"
description: "Lint Yaml files using yamllint"

inputs:
  file_or_dir:
    description: "Files to check"
    required: false
  config_file:
    description: "Path to a custom configuration"
    required: false
  strict:
    description: "Return non-zero exit code on warnings as well as errors"
    required: false
    default: "false"

outputs:
  logs:
    description: "Logs of yamllint"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.file_or_dir }}
    - ${{ inputs.config_file }}
    - ${{ inputs.strict }}
