---
name: "Setup Just"
description: "Setup Just using uvx"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6.7.0

    - name: Install just
      shell: bash
      run: >
        uv tool install rust-just
