---
name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ./.github/actions/yaml-lint

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .github/actions/**/Dockerfile
          recursive: true

      - name: Run shell linter
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHELLCHECK_OPTS: --external-sources --exclude=SC2129
          SHFMT_OPTS: --indent 4 --space-redirects
