---
name: Lint

on:
  workflow_call:
    inputs:
      megalinter-config:
        description: "Path to megalinter config file"
        default: "./.github/linters/.megalinter.yml"
        type: string

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out the codebase
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run megalinter
        uses: oxsecurity/megalinter/flavors/cupcake@15e5b45552097e318c93de385779ce3b1084052c # v10.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEGALINTER_CONFIG: ${{ inputs.megalinter-config }}

          ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES: GITHUB_TOKEN
