---
on:
  workflow_call:
    inputs:
      # General
      working-directory:
        description: "The working directory to run the workflow in."
        default: "./ansible"
        type: string

      # Workflow specific
      molecule:
        description: "Whether to run molecule."
        default: true
        type: boolean

      yamllint:
        description: "Whether to run yamllint."
        default: false
        type: boolean

      yamllint-config:
        description: "The yamllint configuration file to use. Relative to the working directory."
        type: string

      ansible-lint:
        description: "Whether to run ansible-lint."
        default: false
        type: boolean

      ansible-lint-config:
        description: "The ansible-lint configuration file to use. Relative to the working directory."
        type: string

    secrets:
      VAULT_PASSWORD:
        description: "The password used for ansible vault encryption."

jobs:
  molecule:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create vault password file.
        if: inputs.molecule
        run: >
          echo "${{ secrets.VAULT_PASSWORD }}" > $GITHUB_WORKSPACE/${{ inputs.working-directory }}/vault_password.txt

      - name: Run molecule tests.
        if: inputs.molecule
        uses: daniel-mizsak/workflows/.github/actions/molecule@main
        with:
          ANSIBLE_VAULT_PASSWORD_FILE: $GITHUB_WORKSPACE/${{ inputs.working-directory }}/vault_password.txt

      - name: Run ansible-lint.
        if: inputs.ansible-lint
        uses: super-linter/super-linter@v6
        env:
          ANSIBLE_CONFIG_FILE: ${{ inputs.ansible-lint-config }}

      - name: Run yamllint.
        if: inputs.yamllint
        uses: super-linter/super-linter@v6
        env:
          YAMLLINT_CONFIG_FILE: ${{ inputs.yamllint-config }}

