---
on:
  workflow_call:
    inputs:
      working_directory:
        description: "Directory for running the workflow"
        default: "./ansible"
        type: string

    secrets:
      VAULT_PASSWORD:
        description: "The password used for ansible vault encryption"

jobs:
  molecule:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: >
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: >
          pip install molecule molecule-plugins[docker]

      - name: Create vault password file
        run: >
          echo "${{ secrets.VAULT_PASSWORD }}" > $GITHUB_WORKSPACE/${{ inputs.working_directory }}/vault_password.txt

      - name: Run molecule tests
        run: >
          molecule test
        env:
          ANSIBLE_FORCE_COLOR: "1"
          ANSIBLE_VAULT_PASSWORD_FILE: $GITHUB_WORKSPACE/${{ inputs.working_directory }}/vault_password.txt
          PY_COLORS: "1"
