---
name: Prek

on:
  workflow_call:
    inputs:
      extra-args:
        description: "Additional arguments for prek"
        default: "--all-files"
        type: string
      skip:
        description: "Comma-separated list of hooks or projects to skip"
        required: false
        type: string

permissions: {}

jobs:
  prek:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the codebase
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run prek
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        with:
          extra-args: "${{ inputs.extra-args }}"
        env:
          PREK_SKIP: ${{ inputs.skip }}
