---
name: Python CI

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory for running the workflow"
        default: "."
        type: string

      package-version:
        description: |
          Override version specified in pyproject.toml
          Recommended to be used with GitHub releases
        required: false
        type: string

      python-version:
        description: "Python version installed by uv"
        required: false
        type: string

      coverage:
        description: |
          Whether to upload .artifacts/htmlcov to github
          Path is relative to working-directory
        default: false
        type: boolean

      codecov:
        description: |
          Whether to upload .artifacts/coverage.xml to github and codecov
          Path is relative to working-directory
        default: false
        type: boolean

      documentation:
        description: |
          Whether to upload .artifacts/site to github
          Path is relative to working-directory
        default: false
        type: boolean

      package:
        description: |
          Whether to upload .artifacts/dist to github
          Path is relative to working-directory
        default: false
        type: boolean

permissions: {}

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    permissions:
      contents: read
    steps:
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install just
        # kics-scan ignore-line
        uses: daniel-mizsak/workflows/.github/actions/setup-just@main # zizmor: ignore[unpinned-uses]
        with:
          python-version: ${{ inputs.python-version }}

      - name: Run quality checks with just
        run: |
          just install
          just check-all

      - name: Upload coverage artifacts
        if: ${{ inputs.coverage }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: htmlcov
          path: ${{ inputs.working-directory }}/.artifacts/htmlcov
          if-no-files-found: error

      - name: Upload codecov input artifact
        if: ${{ inputs.codecov }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-xml
          path: ${{ inputs.working-directory }}/.artifacts/coverage.xml
          if-no-files-found: error

      - name: Build documentation
        if: ${{ inputs.documentation }}
        run: >
          just build-documentation

      - name: Archive documentation artifacts
        # Inspired by: https://github.com/actions/upload-pages-artifact/blob/main/action.yml
        if: ${{ inputs.documentation }}
        run: >
          tar --directory=".artifacts/site" --create --file .artifacts/site.tar .

      - name: Upload documentation artifacts
        if: ${{ inputs.documentation }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: site
          path: ${{ inputs.working-directory }}/.artifacts/site.tar
          if-no-files-found: error

      - name: Set package version
        if: ${{ inputs.package && inputs.package-version }}
        env:
          UV_PACKAGE_VERSION: ${{ inputs.package-version }}
        run: >
          uv version "${UV_PACKAGE_VERSION}"

      - name: Build package
        if: ${{ inputs.package }}
        run: >
          just build-package

      - name: Upload package artifacts
        if: ${{ inputs.package }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist
          path: ${{ inputs.working-directory }}/.artifacts/dist
          if-no-files-found: error

  codecov:
    if: ${{ inputs.codecov }}
    needs: python-ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # Based on the documentation it is not enough to call the codecov action with only coverage.xml,
      # the checkout action also needs to run: https://github.com/codecov/codecov-action#usage
      - name: Check out the codebase
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Download codecov input artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: coverage-xml
          path: ${{ inputs.working-directory }}/.artifacts

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          fail_ci_if_error: true
          files: ${{ inputs.working-directory }}/.artifacts/coverage.xml
          use_oidc: true
          verbose: true
