---
name: "Python CI/CD"

on:
  workflow_call:
    inputs:
      working_directory:
        description: "Directory for running the workflow"
        default: "."
        type: string

      python_versions:
        description: "List of python versions, must correspond to tox configuration"
        default: "['3.12']"
        type: string

      codecov:
        description: "Whether to upload coverage artifacts and publish to codecov"
        default: false
        type: boolean

      docs:
        description: "Whether to upload documentation artifacts"
        default: false
        type: boolean

    secrets:
      CODECOV_TOKEN:
        description: "Token to use for codecov"
        required: false

jobs:
  tox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python_versions) }}

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: >
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: >
          pip install tox tox-gh

      - name: Run tests with tox
        run: >
          tox

      - name: Upload codecov artifacts
        if: inputs.codecov
        uses: actions/upload-artifact@v4
        with:
          name: codecov
          path: .tox/artifacts/coverage.xml
          if-no-files-found: ignore

      - name: Upload docs artifacts
        if: inputs.docs
        uses: actions/upload-pages-artifact@v3
        with:
          name: docs
          path: .tox/artifacts/docs
        # TODO: Use if-no-files-found: ignore once it is available

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .tox/artifacts/dist
          if-no-files-found: ignore


  codecov-publish:
    needs: tox
    runs-on: ubuntu-latest

    steps:
      - name: Download codecov artifacts
        uses: actions/download-artifact@v4
        with:
          name: codecov
          path: coverage.xml

      - name: Publish codecov artifacts to codecov.io
        if: inputs.codecov
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
