---
name: "Python CI/CD"

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Directory for running the workflow"
        default: "."
        type: string

      python-versions:
        description: "List of python versions, must correspond to tox configuration"
        default: "['3.12']"
        type: string

      codecov:
        description: |
          Whether to upload coverage to codecov
          It assumes that tox generates coverage.xml
        default: false
        type: boolean

    secrets:
      CODECOV_TOKEN:
        description: "Token to use for codecov"
        required: false

jobs:
  tox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python-versions) }}
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Setup tox
        uses: daniel-mizsak/workflows/.github/actions/setup-tox@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests with tox
        run: >
          tox

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage
          path: .tox/artifacts/htmlcov
          if-no-files-found: ignore

      - name: Upload coverage to codecov
        if: ${{ inputs.codecov }}
        run: |
          if [[ -f ".tox/artifacts/coverage.xml" ]]; then
            codecovcli upload-process --file .tox/artifacts/coverage.xml --fail-on-error --token "${{ secrets.CODECOV_TOKEN }}"
          fi

      - name: Archive docs artifacts
        # Inspired by: https://github.com/actions/upload-pages-artifact/blob/main/action.yml
        run: |
          if [[ -d ".tox/artifacts/docs" ]]; then
            tar --create --file .tox/artifacts/docs.tar .tox/artifacts/docs
          fi

      - name: Upload archived docs artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: docs
          path: .tox/artifacts/docs.tar
          if-no-files-found: ignore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build
          path: .tox/artifacts/dist
          if-no-files-found: ignore
